version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            APP_ENV: production
            APP_DEBUG: false
            APP_KEY: '${APP_KEY}'
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: '${DB_DATABASE}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './:/var/www/html'  # Application code
        depends_on:
            - db
        expose:
            - 9000  # Expose PHP-FPM port for Nginx

    nginx:
        image: nginx:latest
        volumes:
            - './nginx.conf:/etc/nginx/nginx.conf'  # Your custom Nginx configuration
            - './:/var/www/html'  # Application code
        ports:
            - '80:80'  # Expose port 80 for web traffic
        depends_on:
            - app

    db:
        image: mysql/mysql-server:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
