version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: always
        environment:
            APP_ENV: production
            APP_DEBUG: false
            APP_KEY: '${APP_KEY}' # Set this in your .env file
            DB_CONNECTION: mysql
            DB_HOST: '${DB_HOST}' # Use a managed database host in production
            DB_PORT: '${DB_PORT}'
            DB_DATABASE: '${DB_DATABASE}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '80:80' # Expose port 80 for HTTP
        volumes:
            - './storage:/var/www/html/storage'
            - './nginx/default.conf:/etc/nginx/sites-available/default' # Mount the Nginx config
        depends_on:
            - db
            - nginx

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - './nginx/default.conf:/etc/nginx/nginx.conf' # Mount the Nginx config
            - './:/var/www/html' # Mount the app folder
        depends_on:
            - app

    db:
        image: mysql/mysql-server:8.0
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
